import type { Metadata } from "next";
import "./globals.css";
import { primaryFont } from "../functions/font";
import { Sidebar } from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={primaryFont.variable}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
